export const members_2024 = [
  {
    id: 0,
    name: "Vishal",
    position: "Red Teamer",
    github: "https://github.com/dfvsd",
    linkedin: "https://www.linkedin.com/in/dvsdfvs",
    instagram: "https://www.instagram.com/dfvsdvf/",
    email: "mailto:rrvfdgb@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 1,
    name: "Kishore Ram ",
    position: "ALL AREA GILLI",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:hari.haran@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 2,
    name: "Abiya Primency",
    position: "Hardware ",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:hari.haran@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 3,
    name: "Subhash",
    position: "Bug Hunter",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:subhash@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 4,
    name: "Shriram Krithick",
    position: "Web Pentester",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:shriram.krithick@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 5,
    name: "Pradyun",
    position: "Web Pentester",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:pradyun@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 6,
    name: "Hari Haran",
    position: "ALL AREA GILLI",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:hari.haran@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
  {
    id: 7,
    name: "Manoj Kumar",
    position: "Network puli",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:manoj.kumar@gmail.com",
    hackthebox: "https://www.hackthebox.com/user/johndoe",
  },
];
