export const members_2024 = [
  {
    id: 0,
    name: "Vishal",
    position: "Red Teamer",
    github: "https://github.com/dfvsd",
    linkedin: "https://www.linkedin.com/in/dvsdfvs",
    instagram: "https://www.instagram.com/dfvsdvf/",
    email: "mailto:vishal.20au@kct.ac.in",
    hackthebox: "https://app.hackthebox.com/users/736565",
  },
  // {
  //   id: 1,
  //   name: "Kishore Ram ",
  //   position: "Reverse Engineer & Network Security",
  //   github: "#",
  //   linkedin: "#",
  //   instagram: "#",
  //   email: "mailto:kishoreram.20ec@kct.ac.in",
  //   hackthebox: "https://app.hackthebox.com/users/1216484",
  // },
  {
    id: 1,
    name: "Abiya Primency",
    position: "Hardware Security Researcher",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:abiyaprimency.20ei@kct.ac.in",
    hackthebox: "",
  },
  {
    id: 2,
    name: "Subhash",
    position: "Bug Bounty Hunter",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:subhash@gmail.com",
    hackthebox: "https://app.hackthebox.com/users/1091202",
  },
  {
    id: 3,
    name: "Shriram Krithick",
    position: "Web Security Analyst & OSINT",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:shriram.krithick@gmail.com",
    hackthebox: "https://app.hackthebox.com/users/1247714",
  },
  {
    id: 4,
    name: "Pradyun",
    position: "Web Pentester",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:pradyun.22ec@kct.ac.in",
    hackthebox: "https://app.hackthebox.com/users/1588827",
  },
  {
    id: 5,
    name: "Hari Haran",
    position: "Reverse Engineer",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:hari.haran@gmail.com",
    hackthebox: "https://app.hackthebox.com/users/1789469",
  },
  {
    id: 6,
    name: "Manoj Kumar",
    position: "Network Security",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "mailto:manoj.kumar@gmail.com",
    hackthebox: "",
  },
];
